develop-install:
	cd as-ap-currinfo; make develop-install
	cd as-ap-injctrl; make develop-install
	cd as-ap-machshift; make develop-install
	cd as-ap-opticscorr; make develop-install
	cd as-ap-posang; make develop-install
	cd as-ap-sofb; make develop-install
	cd as-ps; make develop-install
	cd as-ps-diag; make develop-install
	cd as-pu-conv; make develop-install
	cd as-pu-diag; make develop-install
	cd as-rf-diag; make develop-install
	cd as-ti-control; make develop-install
	cd li-ap-diag; make develop-install
	cd li-ap-energy; make develop-install
	cd li-ps-conv; make develop-install
	cd si-ap-fofb; make develop-install
	cd si-ap-manaca; make develop-install
	cd si-id-conv; make develop-install
	cd si-ps-conv-fastcorrs; make develop-install

develop-uninstall:
	cd as-ap-currinfo; make develop-uninstall
	cd as-ap-injctrl; make develop-uninstall
	cd as-ap-machshift; make develop-uninstall
	cd as-ap-opticscorr; make develop-uninstall
	cd as-ap-posang; make develop-uninstall
	cd as-ap-sofb; make develop-uninstall
	cd as-ps; make develop-uninstall
	cd as-ps-diag; make develop-uninstall
	cd as-pu-conv; make develop-uninstall
	cd as-pu-diag; make develop-uninstall
	cd as-rf-diag; make develop-uninstall
	cd as-ti-control; make develop-uninstall
	cd li-ap-diag; make develop-uninstall
	cd li-ap-energy; make develop-uninstall
	cd li-ps-conv; make develop-uninstall
	cd si-ap-fofb; make develop-uninstall
	cd si-ap-manaca; make develop-uninstall
	cd si-id-conv; make develop-uninstall
	cd si-ps-conv-fastcorrs; make develop-uninstall

install:
	cd as-ap-currinfo; make install
	cd as-ap-injctrl; make install
	cd as-ap-machshift; make install
	cd as-ap-opticscorr; make install
	cd as-ap-posang; make install
	cd as-ap-sofb; make install
	cd as-ps; make install
	cd as-ps-diag; make install
	cd as-pu-conv; make install
	cd as-pu-diag; make install
	cd as-rf-diag; make install
	cd as-ti-control; make install
	cd li-ap-diag; make install
	cd li-ap-energy; make install
	cd li-ps-conv; make install
	cd si-ap-fofb; make install
	cd si-ap-manaca; make install
	cd si-id-conv; make install
	cd si-ps-conv-fastcorrs; make install

uninstall:
	cd as-ap-currinfo; make uninstall
	cd as-ap-injctrl; make uninstall
	cd as-ap-machshift; make uninstall
	cd as-ap-opticscorr; make uninstall
	cd as-ap-posang; make uninstall
	cd as-ap-sofb; make uninstall
	cd as-ps; make uninstall
	cd as-ps-diag; make uninstall
	cd as-pu-conv; make uninstall
	cd as-pu-diag; make uninstall
	cd as-rf-diag; make uninstall
	cd as-ti-control; make uninstall
	cd li-ap-diag; make uninstall
	cd li-ap-energy; make uninstall
	cd li-ps-conv; make uninstall
	cd si-ap-fofb; make uninstall
	cd si-ap-manaca; make uninstall
	cd si-id-conv; make uninstall
	cd si-ps-conv-fastcorrs; make uninstall

clean:
	cd as-ap-currinfo; make clean
	cd as-ap-injctrl; make clean
	cd as-ap-machshift; make clean
	cd as-ap-opticscorr; make clean
	cd as-ap-posang; make clean
	cd as-ap-sofb; make clean
	cd as-ps; make clean
	cd as-ps-diag; make clean
	cd as-pu-conv; make clean
	cd as-pu-diag; make clean
	cd as-rf-diag; make clean
	cd as-ti-control; make clean
	cd li-ap-diag; make clean
	cd li-ap-energy; make clean
	cd li-ps-conv; make clean
	cd si-ap-fofb; make clean
	cd si-ap-manaca; make clean
	cd si-id-conv; make clean
	cd si-ps-conv-fastcorrs; make clean
