
install-tb:
	@printf "Installing sirius-ioc-tb-ps-diag service...\n"
	cp -rf sirius-ioc-tb-ps-diag.service /etc/systemd/system/
	mkdir -p /home/sirius/iocs-log
	systemctl daemon-reload

stop-tb:
	@printf "Stopping  sirius-ioc-tb-ps-diag...\n"
	systemctl stop sirius-ioc-tb-ps-diag.service

start-tb:
	@printf "Starting  sirius-ioc-tb-ps-diag...\n"
	systemctl start sirius-ioc-tb-ps-diag.service

uninstall-tb: stop-tb
	@printf "Uninstalling  sirius-ioc-tb-ps-diag...\n"
	systemctl disable sirius-ioc-tb-ps-diag.service
	rm -rf /etc/systemd/system/sirius-ioc-tb-ps-diag.service
	systemctl daemon-reload
	systemctl reset-failed


install-bo:
	@printf "Installing sirius-ioc-bo-ps-diag service...\n"
	cp -rf sirius-ioc-bo-ps-diag.service /etc/systemd/system/
	mkdir -p /home/sirius/iocs-log
	systemctl daemon-reload

stop-bo:
	@printf "Stopping  sirius-ioc-bo-ps-diag...\n"
	systemctl stop sirius-ioc-bo-ps-diag.service

start-bo:
	@printf "Starting  sirius-ioc-bo-ps-diag...\n"
	systemctl start sirius-ioc-bo-ps-diag.service

uninstall-bo: stop-bo
	@printf "Uninstalling  sirius-ioc-bo-ps-diag...\n"
	systemctl disable sirius-ioc-bo-ps-diag.service
	rm -rf /etc/systemd/system/sirius-ioc-bo-ps-diag.service
	systemctl daemon-reload
	systemctl reset-failed


install-ts:
	@printf "Installing sirius-ioc-ts-ps-diag service...\n"
	cp -rf sirius-ioc-ts-ps-diag.service /etc/systemd/system/
	mkdir -p /home/sirius/iocs-log
	systemctl daemon-reload

stop-ts:
	@printf "Stopping  sirius-ioc-ts-ps-diag...\n"
	systemctl stop sirius-ioc-ts-ps-diag.service

start-ts:
	@printf "Starting  sirius-ioc-ts-ps-diag...\n"
	systemctl start sirius-ioc-ts-ps-diag.service

uninstall-ts: stop-ts
	@printf "Uninstalling  sirius-ioc-ts-ps-diag...\n"
	systemctl disable sirius-ioc-ts-ps-diag.service
	rm -rf /etc/systemd/system/sirius-ioc-ts-ps-diag.service
	systemctl daemon-reload
	systemctl reset-failed


install-si-fam:
	@printf "Installing sirius-ioc-si-ps-diag-fam service...\n"
	cp -rf sirius-ioc-si-ps-diag-fam.service /etc/systemd/system/
	mkdir -p /home/sirius/iocs-log
	systemctl daemon-reload

stop-si-fam:
	@printf "Stopping  sirius-ioc-si-ps-diag-fam...\n"
	systemctl stop sirius-ioc-si-ps-diag-fam.service

start-si-fam:
	@printf "Starting  sirius-ioc-si-ps-diag-fam...\n"
	systemctl start sirius-ioc-si-ps-diag-fam.service

uninstall-si-fam: stop-si-fam
	@printf "Uninstalling  sirius-ioc-si-ps-diag-fam...\n"
	systemctl disable sirius-ioc-si-ps-diag-fam.service
	rm -rf /etc/systemd/system/sirius-ioc-si-ps-diag-fam.service
	systemctl daemon-reload
	systemctl reset-failed


install-si-ch:
	@printf "Installing sirius-ioc-si-ps-diag-ch service...\n"
	cp -rf sirius-ioc-si-ps-diag-ch.service /etc/systemd/system/
	mkdir -p /home/sirius/iocs-log
	systemctl daemon-reload

stop-si-ch:
	@printf "Stopping  sirius-ioc-si-ps-diag-ch...\n"
	systemctl stop sirius-ioc-si-ps-diag-ch.service

start-si-ch:
	@printf "Starting  sirius-ioc-si-ps-diag-ch...\n"
	systemctl start sirius-ioc-si-ps-diag-ch.service

uninstall-si-ch: stop-si-ch
	@printf "Uninstalling  sirius-ioc-si-ps-diag-ch...\n"
	systemctl disable sirius-ioc-si-ps-diag-ch.service
	rm -rf /etc/systemd/system/sirius-ioc-si-ps-diag-ch.service
	systemctl daemon-reload
	systemctl reset-failed


install-si-cv:
	@printf "Installing sirius-ioc-si-ps-diag-cv service...\n"
	cp -rf sirius-ioc-si-ps-diag-cv.service /etc/systemd/system/
	mkdir -p /home/sirius/iocs-log
	systemctl daemon-reload

stop-si-cv:
	@printf "Stopping  sirius-ioc-si-ps-diag-cv...\n"
	systemctl stop sirius-ioc-si-ps-diag-cv.service

start-si-cv:
	@printf "Starting  sirius-ioc-si-ps-diag-cv...\n"
	systemctl start sirius-ioc-si-ps-diag-cv.service

uninstall-si-cv: stop-si-cv
	@printf "Uninstalling  sirius-ioc-si-ps-diag-cv...\n"
	systemctl disable sirius-ioc-si-ps-diag-cv.service
	rm -rf /etc/systemd/system/sirius-ioc-si-ps-diag-cv.service
	systemctl daemon-reload
	systemctl reset-failed


install-si-qs:
	@printf "Installing sirius-ioc-si-ps-diag-qs service...\n"
	cp -rf sirius-ioc-si-ps-diag-qs.service /etc/systemd/system/
	mkdir -p /home/sirius/iocs-log
	systemctl daemon-reload

stop-si-qs:
	@printf "Stopping  sirius-ioc-si-ps-diag-qs...\n"
	systemctl stop sirius-ioc-si-ps-diag-qs.service

start-si-qs:
	@printf "Starting  sirius-ioc-si-ps-diag-qs...\n"
	systemctl start sirius-ioc-si-ps-diag-qs.service

uninstall-si-qs: stop-si-qs
	@printf "Uninstalling  sirius-ioc-si-ps-diag-qs...\n"
	systemctl disable sirius-ioc-si-ps-diag-qs.service
	rm -rf /etc/systemd/system/sirius-ioc-si-ps-diag-qs.service
	systemctl daemon-reload
	systemctl reset-failed


install-si-trim-q1234:
	@printf "Installing sirius-ioc-si-ps-diag-trim-q1234 service...\n"
	cp -rf sirius-ioc-si-ps-diag-trim-q1234.service /etc/systemd/system/
	mkdir -p /home/sirius/iocs-log
	systemctl daemon-reload

stop-si-trim-q1234:
	@printf "Stopping  sirius-ioc-si-ps-diag-trim-q1234...\n"
	systemctl stop sirius-ioc-si-ps-diag-trim-q1234.service

start-si-trim-q1234:
	@printf "Starting  sirius-ioc-si-ps-diag-trim-q1234...\n"
	systemctl start sirius-ioc-si-ps-diag-trim-q1234.service

uninstall-si-trim-q1234: stop-si-trim-q1234
	@printf "Uninstalling  sirius-ioc-si-ps-diag-trim-q1234...\n"
	systemctl disable sirius-ioc-si-ps-diag-trim-q1234.service
	rm -rf /etc/systemd/system/sirius-ioc-si-ps-diag-trim-q1234.service
	systemctl daemon-reload
	systemctl reset-failed


install-si-trim-qfqd:
	@printf "Installing sirius-ioc-si-ps-diag-trim-qfqd service...\n"
	cp -rf sirius-ioc-si-ps-diag-trim-qfqd.service /etc/systemd/system/
	mkdir -p /home/sirius/iocs-log
	systemctl daemon-reload

stop-si-trim-qfqd:
	@printf "Stopping  sirius-ioc-si-ps-diag-trim-qfqd...\n"
	systemctl stop sirius-ioc-si-ps-diag-trim-qfqd.service

start-si-trim-qfqd:
	@printf "Starting  sirius-ioc-si-ps-diag-trim-qfqd...\n"
	systemctl start sirius-ioc-si-ps-diag-trim-qfqd.service

uninstall-si-trim-qfqd: stop-si-trim-qfqd
	@printf "Uninstalling  sirius-ioc-si-ps-diag-trim-qfqd...\n"
	systemctl disable sirius-ioc-si-ps-diag-trim-qfqd.service
	rm -rf /etc/systemd/system/sirius-ioc-si-ps-diag-trim-qfqd.service
	systemctl daemon-reload
	systemctl reset-failed


install-si-fc:
	@printf "Installing sirius-ioc-si-ps-diag-fc service...\n"
	cp -rf sirius-ioc-si-ps-diag-fc.service /etc/systemd/system/
	mkdir -p /home/sirius/iocs-log
	systemctl daemon-reload

stop-si-fc:
	@printf "Stopping  sirius-ioc-si-ps-diag-fc...\n"
	systemctl stop sirius-ioc-si-ps-diag-fc.service

start-si-fc:
	@printf "Starting  sirius-ioc-si-ps-diag-fc...\n"
	systemctl start sirius-ioc-si-ps-diag-fc.service

uninstall-si-fc: stop-si-fc
	@printf "Uninstalling  sirius-ioc-si-ps-diag-fc...\n"
	systemctl disable sirius-ioc-si-ps-diag-fc.service
	rm -rf /etc/systemd/system/sirius-ioc-si-ps-diag-fc.service
	systemctl daemon-reload
	systemctl reset-failed


install-si: install-si-fam install-si-ch install-si-cv install-si-qs install-si-trim-q1234 install-si-trim-qfqd install-si-fc

stop-si: stop-si-fam stop-si-ch stop-si-cv stop-si-qs stop-si-trim-q1234 stop-si-trim-qfqd stop-si-fc

start-si: start-si-fam start-si-ch start-si-cv start-si-qs start-si-trim-q1234 start-si-trim-qfqd start-si-fc

uninstall-si: uninstall-si-fam uninstall-si-ch uninstall-si-cv uninstall-si-qs uninstall-si-trim-q1234 uninstall-si-trim-qfqd uninstall-si-fc


# --- ALL ACCELERATORS ---

install-services: install-tb install-bo install-ts install-si

stop: stop-tb stop-bo stop-ts stop-si

start: start-tb start-bo start-ts start-si

uninstall: uninstall-tb uninstall-bo uninstall-ts uninstall-si

uninstall-services: uninstall
