['EPU']
min_gap=+22
max_gap=+300
min_phase=-25
max_phase=+25
#drive_a_port='/dev/ttyS1'
#drive_b_port='/dev/ttyUSB0'
#drive_a_address=21
#drive_b_address=21
drive_A_address=21
drive_B_address=21
drive_S_address=21
drive_I_address=21
baud_rate=19200
