['EPU']
drive_A_address=21
drive_B_address=21
drive_S_address=21
drive_I_address=21
baud_rate=19200
min_gap=+22
max_gap=+300
min_phase=-25
max_phase=+25
ecodrive_log_file_path='ecodrive_control.log'
epu_log_file_path='epu_control.log'

[EPU2]
MINIMUN_GAP=+22
MAXIMUM_GAP=+300
MINIMUM_PHASE=-25
MAXIMUM_PHASE=+25
SERIAL_PORT='/dev/pts/12'
A_DRIVE_ADDRESS=21
B_DRIVE_ADDRESS=22
I_DRIVE_ADDRESS=11
S_DRIVE_ADDRESS=12
BAUD_RATE=19200
ECODRIVE_LOG_FILE_PATH='ecodrive_control.log'
EPU_LOG_FILE_PATH='epu_control.log'
