['EPU']
min_gap=+22
max_gap=+300
min_phase=-25
max_phase=+25
#drive_a_port='/dev/ttyS1'
#drive_b_port='/dev/ttyUSB0'
#drive_a_address=21
#drive_b_address=21
drive_A_address=21
drive_B_address=21
drive_S_address=21
drive_I_address=21
baud_rate=19200

[EPU2]
MINIMUN_GAP=+22
MAXIMUM_GAP=+300
MINIMUM_PHASE=-25
MAXIMUM_PHASE=+25
SERIAL_PORT='/dev/USB0'
A_DRIVE_ADDRESS=21
B_DRIVE_ADDRESS=21
I_DRIVE_ADDRESS=21
S_DRIVE_ADDRESS=21
BAUD_RATE=19200
ECODRIVE_LOG_FILE_PATH='ecodrive_control.log'
EPU_LOG_FILE_PATH='epu_control.log'
