['EPU']
A_DRIVE_ADDRESS=21
B_DRIVE_ADDRESS=22
S_DRIVE_ADDRESS=12
I_DRIVE_ADDRESS=11
BAUD_RATE=19200
MINIMUM_GAP=+22
MAXIMUM_GAP=+300
MINIMUM_PHASE=-25
MAXIMUM_PHASE=+25
MAXIMUM_VELOCITY=+500
ECODRIVE_LOG_FILE_PATH='ecodrive_control.log'
EPU_LOG_FILE_PATH='epu_control.log'
