
diagnostic_messages:
  C204h: 'C204 - Motor type P-0-4014 incorrect'
  F644h: 'F644 - Negative travel limit switch detected'
  E834h: 'E834 - Emergency-Stop active'
  A013h: 'A013 - Ready for power on'
messages:
  0: 'P0'
  1: 'P1'
  2: 'P2'
  3: 'P3'
  10: 'AH'
  12: 'Ab'
  13: 'bb'
  18: 'Jb'
  208: 'JF'
  211: 'AF'
  400: 'AC'