
MINIMUN_GAP=+22
MAXIMUM_GAP=+300
MINIMUM_PHASE=-25
MAXIMUM_PHASE=+25
DRIVE_A_SERIAL_PORT='/dev/USB0'
DRIVE_B_SERIAL_PORT='/dev/ttyUSB0'
DRIVE_A_ADDRESS=21
DRIVE_A_ADDRESS=21
BAUD_RATE=19200

LOG_FILE_PATH='epu_control.log'